import React from "react";
import { CurrencyCircleDollar, Gauge, Lock, Wallet } from "@phosphor-icons/react";
import { PlannerState } from "@/features/planner/types";

type PlanPreviewHighlightSection =
  | "overview"
  | "kpis"
  | "venue"
  | "inventory"
  | "timeline"
  | "budget";

type PlanPreviewCanvasProps = {
  planData: PlannerState | null;
  highlightSection?: PlanPreviewHighlightSection;
};

const currencyFormatter = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  maximumFractionDigits: 0
});

const donutColors = ["#0f766e", "#1d4ed8", "#ea580c", "#9333ea", "#475569"];

const BudgetDonut: React.FC<{ breakdown: PlannerState["budget"]["breakdown"] }> = ({
  breakdown
}) => {
  const size = 144;
  const strokeWidth = 16;
  const radius = (size - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const totalPct = Math.max(
    1,
    breakdown.reduce((sum, item) => sum + item.pct, 0)
  );

  let accumulated = 0;
  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} className="-rotate-90">
      <circle
        cx={size / 2}
        cy={size / 2}
        r={radius}
        fill="none"
        stroke="#e2e8f0"
        strokeWidth={strokeWidth}
      />
      {breakdown.map((entry, index) => {
        const pctNormalized = entry.pct / totalPct;
        const segmentLength = pctNormalized * circumference;
        const dashOffset = circumference - accumulated;
        accumulated += segmentLength;

        return (
          <circle
            key={`${entry.label}-${index}`}
            cx={size / 2}
            cy={size / 2}
            r={radius}
            fill="none"
            stroke={donutColors[index % donutColors.length]}
            strokeWidth={strokeWidth}
            strokeDasharray={`${segmentLength} ${circumference}`}
            strokeDashoffset={dashOffset}
            strokeLinecap="butt"
          />
        );
      })}
    </svg>
  );
};

const PlanPreviewCanvas: React.FC<PlanPreviewCanvasProps> = ({
  planData,
  highlightSection
}) => {
  if (!planData) {
    return <aside className="h-full min-h-0 bg-white" aria-label="Canvas preview panel" />;
  }

  const hasTimelineEntries = planData.timeline.length > 0;
  const hasBudgetBreakdown = planData.budget.breakdown.length > 0;

  return (
    <aside className="h-full min-h-0 overflow-y-auto overscroll-y-contain bg-white" aria-label="Canvas preview panel">
      <header
        id="canvas-overview"
        className={`sticky top-0 z-10 border-b border-slate-200 bg-white/95 px-5 py-4 backdrop-blur ${
          highlightSection === "overview" ? "bg-brand-teal/5" : ""
        }`}
      >
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">
              Canvas Preview
            </p>
            <h2 className="mt-1 truncate text-lg font-semibold text-slate-900">{planData.title}</h2>
            <p className="mt-1 line-clamp-2 text-xs text-slate-600">{planData.summary}</p>
          </div>
          <div className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[11px] text-slate-600">
            <Lock className="h-3 w-3" />
            Generated by AI - use chat to modify
          </div>
        </div>
      </header>

      <div className="space-y-5 p-5">
        <section
          id="canvas-kpis"
          className={`grid grid-cols-3 gap-2 rounded-2xl p-1 ${
            highlightSection === "kpis" ? "bg-brand-teal/5" : ""
          }`}
        >
          <article className="rounded-xl border border-slate-200 bg-slate-50/80 p-3">
            <div className="flex items-center gap-1 text-[11px] uppercase tracking-[0.12em] text-slate-500">
              <Wallet className="h-3.5 w-3.5" />
              Total Cost
            </div>
            <p className="mt-2 text-sm font-semibold text-slate-900">
              {currencyFormatter.format(planData.kpis.totalCost)}
            </p>
          </article>
          <article className="rounded-xl border border-slate-200 bg-slate-50/80 p-3">
            <div className="flex items-center gap-1 text-[11px] uppercase tracking-[0.12em] text-slate-500">
              <CurrencyCircleDollar className="h-3.5 w-3.5" />
              Cost / Attendee
            </div>
            <p className="mt-2 text-sm font-semibold text-slate-900">
              {currencyFormatter.format(planData.kpis.costPerAttendee)}
            </p>
          </article>
          <article className="rounded-xl border border-slate-200 bg-slate-50/80 p-3">
            <div className="flex items-center gap-1 text-[11px] uppercase tracking-[0.12em] text-slate-500">
              <Gauge className="h-3.5 w-3.5" />
              Confidence
            </div>
            <p className="mt-2 text-sm font-semibold text-slate-900">
              {planData.kpis.confidencePct}%
            </p>
          </article>
        </section>

        <section
          id="canvas-inventory"
          className={`space-y-3 rounded-2xl border border-slate-200 p-4 ${
            highlightSection === "inventory" ? "bg-brand-teal/5" : "bg-slate-50/60"
          }`}
        >
          <h3 className="text-sm font-semibold text-slate-900">Space & Inventory</h3>
          <div id="canvas-venue" className="grid grid-cols-2 gap-2">
            <div className="rounded-xl border border-slate-200 bg-white p-3">
              <p className="text-[11px] uppercase tracking-[0.12em] text-slate-500">Before</p>
              <p className="mt-1 text-sm font-medium text-slate-900">{planData.spacePlan.beforeLabel}</p>
            </div>
            <div className="rounded-xl border border-brand-teal/20 bg-white p-3">
              <p className="text-[11px] uppercase tracking-[0.12em] text-brand-teal">After</p>
              <p className="mt-1 text-sm font-medium text-slate-900">{planData.spacePlan.afterLabel}</p>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-2 text-xs">
            {Object.entries(planData.spacePlan.inventory).map(([key, value]) => (
              <div
                key={key}
                className="flex items-center justify-between rounded-lg border border-slate-200 bg-white px-3 py-2"
              >
                <span className="capitalize text-slate-500">{key}</span>
                <span className="font-semibold text-slate-900">{value}</span>
              </div>
            ))}
          </div>
        </section>

        <section
          id="canvas-timeline"
          className={`space-y-3 rounded-2xl border border-slate-200 p-4 ${
            highlightSection === "timeline" ? "bg-brand-teal/5" : "bg-white"
          }`}
        >
          <h3 className="text-sm font-semibold text-slate-900">Timeline & Dependencies</h3>
          {hasTimelineEntries ? (
            <div className="space-y-3 border-l border-slate-200 pl-3">
              {planData.timeline.map((item, index) => (
                <article key={`${item.time}-${index}`} className="relative">
                  <span className="absolute -left-[1.01rem] top-1 h-2.5 w-2.5 rounded-full bg-brand-teal" />
                  <p className="text-xs font-semibold text-slate-900">
                    {item.time} - {item.title}
                  </p>
                  <p className="mt-1 text-xs text-slate-600">{item.notes}</p>
                </article>
              ))}
            </div>
          ) : null}
        </section>

        <section
          id="canvas-budget"
          className={`space-y-3 rounded-2xl border border-slate-200 p-4 ${
            highlightSection === "budget" ? "bg-brand-teal/5" : "bg-white"
          }`}
        >
          <h3 className="text-sm font-semibold text-slate-900">Budget Simulation</h3>
          {hasBudgetBreakdown ? (
            <div className="flex items-center gap-4">
              <BudgetDonut breakdown={planData.budget.breakdown} />
              <div className="flex-1 space-y-2">
                {planData.budget.breakdown.map((item, index) => (
                  <div key={item.label} className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2 text-slate-600">
                      <span
                        className="h-2.5 w-2.5 rounded-full"
                        style={{ backgroundColor: donutColors[index % donutColors.length] }}
                      />
                      {item.label}
                    </div>
                    <span className="font-semibold text-slate-900">{item.pct}%</span>
                  </div>
                ))}
                <p className="pt-2 text-xs text-slate-600">
                  Total: {currencyFormatter.format(planData.budget.total)}
                </p>
                {planData.budget.tradeoffNote && (
                  <p className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-600">
                    {planData.budget.tradeoffNote}
                  </p>
                )}
              </div>
            </div>
          ) : null}
        </section>
      </div>
    </aside>
  );
};

export default PlanPreviewCanvas;
